title: MJXGUI
description: A WYSIWYG equation editor for the web with LaTeX support
theme: just-the-docs

url: https://hrushikeshrv.github.io/mjxgui

aux_links:
  "View on GitHub": https://github.com/hrushikeshrv/mjxgui

enable_copy_code_button: true

callouts:
  warning:
    title: Warning
    color: red
  note:
    title: Note
    color: purple

ga_tracking: G-TGM5F6WJNV

nav_external_links:
  - title: View on GitHub
    url: https://github.com/hrushikeshrv/mjxgui
    opens_in_new_tab: true
  - title: Raise an Issue
    url: https://github.com/hrushikeshrv/mjxgui/issues
    opens_in_new_tab: true

favicon_ico: "/media/favicon.png"